### ISSUE TITLE
[question] Is there a way to get a video feed of the camera?

### ISSUE THREAD

**Issue by gorbypark** [AfonsoFGarcia/bluecon#1]
Hey, just poking around various GitHub repos since I'm having a Fermax Veo WiFi system installed tomorrow!  I currently use Scrypted (as a Home Assistant add-on) to feed some rtsp/rtmp video feeds into my HomeKit system as "security cameras".  I had the idea it might be possible to get the video feed from the front door somehow?  It seems this this library has a way to get the latest image, but I'm not seeing anything obvious about video.

To be honest I have no idea how Fermax has this all setup, it's possible there's a persistent video feed, or maybe the customers WiFi unit streams the video when a call comes in?  In an ideal world I'd be able to just get a url for the video feed, but I'm guessing it will be more complicated than that!

Anyways, when I have the unit installed I will start poking around, just thought I'd reach out and say hi / ask the question.

**Comment by AfonsoFGarcia** [comment]
Hey there! Yeah, no way for getting the live video yet. Haven't had time to progress on this to that point.

The entire lib was done by reverse engineering the Android apk. From what I gathered there, the way it works is by using a videoconference platform: when the doorbell is rang, it creates a call, the video doorman joins and the app as well. I suspect the info for it comes as part of some push notification but, once again, haven't had time for it.

If you find out about it, please let me know and if you're up to it feel free to create a PR to add the feature! Would love to have it implemented and added to the Home Assistant integration as well.
